<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="367" started-at="2017-08-28T02:43:35Z" finished-at="2017-08-28T02:43:36Z">
    <groups>
      <group name="update">
        <method signature="WhayerMetaDataManagerImplTest.updateListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="updateListTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
      </group> <!-- update -->
      <group name="query">
        <method signature="WhayerMetaDataManagerImplTest.searchAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="searchAlarmInfoListTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
      </group> <!-- query -->
      <group name="add">
        <method signature="WhayerMetaDataManagerImplTest.savleAlarmMessageLevelMetaListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="savleAlarmMessageLevelMetaListTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
        <method signature="WhayerMetaDataManagerImplTest.savleAlarmMessageLevelMetaTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="savleAlarmMessageLevelMetaTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
      </group> <!-- add -->
      <group name="singleDelete">
        <method signature="WhayerMetaDataManagerImplTest.deleteAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="deleteAlarmInfoListTest" class="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest"/>
      </group> <!-- singleDelete -->
    </groups>
    <test name="Default test" duration-ms="367" started-at="2017-08-28T02:43:35Z" finished-at="2017-08-28T02:43:36Z">
      <class name="com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-08-28T10:43:35Z" finished-at="2017-08-28T10:43:35Z">
          <exception class="org.springframework.beans.factory.CannotLoadBeanClassException">
            <message>
              <![CDATA[Cannot find class [com.whayer.cloud.component.objectcache.impl.ObjectCacheService] for bean with name 'objectCacheService' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: com.whayer.cloud.component.objectcache.impl.ObjectCacheService]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.whayer.cloud.component.objectcache.impl.ObjectCacheService] for bean with name 'objectCacheService' defined in class path resource [beans.xml]; nested exception is java.lang.ClassNotFoundException: com.whayer.cloud.component.objectcache.impl.ObjectCacheService
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:741)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest.beforeTest(WhayerMetaDataManagerImplTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.beforeRun(TestRunner.java:624)
	at org.testng.TestRunner.run(TestRunner.java:592)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: com.whayer.cloud.component.objectcache.impl.ObjectCacheService
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
	... 33 more
]]>
            </full-stacktrace>
          </exception> <!-- org.springframework.beans.factory.CannotLoadBeanClassException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="savleAlarmMessageLevelMetaListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="savleAlarmMessageLevelMetaListTest" duration-ms="2" started-at="2017-08-28T10:43:36Z" finished-at="2017-08-28T10:43:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- savleAlarmMessageLevelMetaListTest -->
        <test-method status="SKIP" signature="savleAlarmMessageLevelMetaTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="savleAlarmMessageLevelMetaTest" duration-ms="2" started-at="2017-08-28T10:43:36Z" finished-at="2017-08-28T10:43:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- savleAlarmMessageLevelMetaTest -->
        <test-method status="SKIP" signature="updateListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="updateListTest" duration-ms="0" depends-on-groups="add" started-at="2017-08-28T10:43:36Z" finished-at="2017-08-28T10:43:36Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method WhayerMetaDataManagerImplTest.updateListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d] depends on not successfully finished methods in group "add"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method WhayerMetaDataManagerImplTest.updateListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d] depends on not successfully finished methods in group "add"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateListTest -->
        <test-method status="SKIP" signature="deleteAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="deleteAlarmInfoListTest" duration-ms="0" depends-on-groups="update" started-at="2017-08-28T10:43:36Z" finished-at="2017-08-28T10:43:36Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method WhayerMetaDataManagerImplTest.deleteAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d] depends on not successfully finished methods in group "update"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method WhayerMetaDataManagerImplTest.deleteAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d] depends on not successfully finished methods in group "update"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAlarmInfoListTest -->
        <test-method status="SKIP" signature="searchAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="searchAlarmInfoListTest" duration-ms="0" depends-on-groups="update, add" started-at="2017-08-28T10:43:36Z" finished-at="2017-08-28T10:43:36Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method WhayerMetaDataManagerImplTest.searchAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d] depends on not successfully finished methods in group "update"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method WhayerMetaDataManagerImplTest.searchAlarmInfoListTest()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d] depends on not successfully finished methods in group "update"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchAlarmInfoListTest -->
        <test-method status="SKIP" signature="afterTese()[pri:0, instance:com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest@3071de8d]" name="afterTese" is-config="true" duration-ms="0" started-at="2017-08-28T10:43:36Z" finished-at="2017-08-28T10:43:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTese -->
      </class> <!-- com.whayer.cloud.storage.component.foundation.meta.impl.WhayerMetaDataManagerImplTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
